### ISSUE TITLE
Completely Wrong answer!

### ISSUE THREAD

**Issue by HarshitDawar55** [mablatnik/Data-Structures-And-Algorithms#5]
Your week 3 largest number is nowhere even closer to the actual solution, so many syntax and semantic mistakes are there. I suggest correct it.

**Comment by kirbyfern** [comment]
@HarshitDawar55 woo woo hold on buddy, there are lots of possible solutions and besides you are correcting a current Salesforce engineer.

**Comment by HarshitDawar55** [comment]
Ya I know but the answer is wrong that is why I said!

**Comment by Ruzdan741** [comment]
Yes, I was looking for the "Maximum Amount of Gold" problem, to which his solution is completely wrong. I request you to please correct it or take it down.

**Comment by HarshitDawar55** [comment]
Created a pull request with the correct solution, waiting for the owner of the repository to merge my solution into his Repository.
